### PR TITLE
Add in post id to promoter notify payload

### PR DESCRIPTION
**Pull request by nealfennimore**
https://central.tri.be/issues/123732

Related to https://github.com/moderntribe/promoter-auth-connector/pull/5

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Each line in an array declaration must end in a comma | [Connector.php:125](https://github.com/moderntribe/tribe-common/blob/427fefc8f30b5ca52528b26aadb07a18543299d3/src/Tribe/Promoter/Connector.php#L125)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Each line in an array declaration must end in a comma | [Connector.php:125](https://github.com/moderntribe/tribe-common/blob/4137ed08e63fe7b83b4388211f76bbc7accd686d/src/Tribe/Promoter/Connector.php#L125)

> via jenkins/codesniffer-phpcs

**Comment by sc0ttkclark** [comment]
PR needs to be marked as ready for review (it's currently draft) to continue

**Comment by mitogh** [comment]
Closing this one to reopen as `ready for review`

**Pull request closed without merging**
