### PR TITLE
Fix incoherencency and scaling issues

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/77988

This PR:

* adds the tests and code to make sure the chunker handles growing and diminishing meta values properly
* adds tests and code to make sure the chunker keeps track of corrupted data in the database; in this instance the database will do "its best" stopping the chunking operations and returning the value as a string
* the chunker will now use and keep a checksum of stored data up to date to verify that the chunks still prove coherent

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Each line in an array declaration must end in a comma | [Chunker.php:316](https://github.com/moderntribe/tribe-common/blob/9766ee4c21b560dc96a56da85f23781096bebaf8/src/Tribe/Meta/Chunker.php#L316)
:x: | Each line in an array declaration must end in a comma | [Chunker.php:463](https://github.com/moderntribe/tribe-common/blob/9766ee4c21b560dc96a56da85f23781096bebaf8/src/Tribe/Meta/Chunker.php#L463)
:x: | Visibility must be declared on method &quot;__destruct&quot; | [Chunker.php:645](https://github.com/moderntribe/tribe-common/blob/9766ee4c21b560dc96a56da85f23781096bebaf8/src/Tribe/Meta/Chunker.php#L645)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
Andras has QAed this ok, good for review

**Comment by barryhughes** [comment]
Is the plan to put this out in an MR? (...if we are, we'll want to target an MR branch/create one if needed)

**Comment by lucatume** [comment]
Ideally yes, I have no idea which branch to target here and on TEC though

**Comment by lucatume** [comment]
Closing this to move PR to MR: https://github.com/moderntribe/tribe-common/pull/387

**Pull request closed without merging**
