### PR TITLE
Add the new and Shiny Common Customize Class

### PR DESCRIPTION
**Pull request by bordoni**
_Ref:_ [C#67489](https://central.tri.be/issues/67489)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Customizer.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L3)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$css_template' | [Customizer.php:408](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L408)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this' | [Customizer.php:413](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L413)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Section.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L3)
:x: | You must have a space after a closing parenthesis | [Section.php:163](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L163)
:x: | You must have a space after a closing parenthesis | [Section.php:168](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L168)
:warning: | The method parameter $customizer is never used | [Section.php:247](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L247)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Color.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Utils/Color.php#L3)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
:bangbang: This Pull Request is against a Central ticket for "Next Release". It shouldn't be merged until the Central ticket has been changed to "Current Release" or "CR Maintenance Release".

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Customizer.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L3)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$css_template' | [Customizer.php:408](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L408)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this' | [Customizer.php:413](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L413)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Section.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L3)
:x: | You must have a space after a closing parenthesis | [Section.php:163](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L163)
:x: | You must have a space after a closing parenthesis | [Section.php:168](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L168)
:warning: | The method parameter $customizer is never used | [Section.php:247](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L247)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Color.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Utils/Color.php#L3)

> via jenkins/codesniffer-phpcs

**Comment by borkweb** [comment]
The ticket this is associated seems to have gone away. Before we throw `merge` back on here, can you re-associate with a different Central ticket?

**Comment by bordoni** [comment]
Resolved Matts concern.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Customizer.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L3)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$css_template' | [Customizer.php:408](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L408)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this' | [Customizer.php:413](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer.php#L413)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Section.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L3)
:x: | You must have a space after a closing parenthesis | [Section.php:163](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L163)
:x: | You must have a space after a closing parenthesis | [Section.php:168](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L168)
:warning: | The method parameter $customizer is never used | [Section.php:247](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Customizer/Section.php#L247)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Color.php:3](https://github.com/moderntribe/tribe-common/blob/f6a128afd6949843dcc3e931b22196abdc4260e0/src/Tribe/Utils/Color.php#L3)

> via jenkins/codesniffer-phpcs

**Pull request merged**
