### PR TITLE
Fix meta chunker tests and handling of filtering operations

### PR DESCRIPTION
**Pull request by lucatume**
Follow-up to the work done for ticket https://central.tri.be/issues/80857

This PR fixes the tests, adds a bunch of filters to control Meta Chunker operations and makes sure we are not handling the meta filtering if not really necessary.
The PR also adds tests and support for the use of `wp_cache_functions` using the same cache group for meta Core uses (`post_meta`).

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | A cast statement must be followed by a single space | [Chunker.php:792](https://github.com/moderntribe/tribe-common/blob/ae8057345163b23757de015bd8a0a63966714259/src/Tribe/Meta/Chunker.php#L792)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Buy Now Button*, but this was pull requested against *release/M17.12*.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Buy Now Button*, but this was pull requested against *release/F17.5*.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Buy Now Button*, but this was pull requested against *release/F17.5*.

**Comment by bordoni** [comment]
Should we keep this closed @lucatume ?

**Comment by lucatume** [comment]
No, thanks for noticing. 
The work done for this has be merged here: https://github.com/moderntribe/tribe-common/pull/421

**Pull request closed without merging**
