### PR TITLE
Update inputs loop for REST API Tester to support checkboxes (checked vs not checked)

### PR DESCRIPTION
**Pull request by sc0ttkclark**

### CODE REVIEW

**Comment by lucatume** [comment]
How would the UI come to have checkboxes? Does this PR relates to a PR I missed?

**Comment by sc0ttkclark** [comment]
Yes that was PR #501 that got merged in for boolean field types. If we see a swagger spec with boolean, we use a checkbox with value=1, but when we introduced that it would submit all checkboxes no matter what. This PR just limits to those with checked prop true. We also now support number inputs as a result of that PR. It works awesome!

**Comment by lucatume** [comment]
The only issue I have with that is that we have just killed the plugin capacity to send a "wrong" value for a boolean field: this is a legit testing scenario.

**Comment by sc0ttkclark** [comment]
If that's the case, I can back the checkboxes/number inputs out.

**Comment by lucatume** [comment]
I say we merge this and, maybe, revert your stuff later.
Better yet: provide a default mode, with UI helps like the ones you put in place, and a test/dev mode to be able to send anything on any field.

**Comment by sc0ttkclark** [comment]
Link next to the checkbox / number input "Custom input" which then converts the input to a normal input type="text" -- that wouldn't be too hard

**Comment by lucatume** [comment]
that's a brilliant idea; noted and good for another PR

**Comment by sc0ttkclark** [comment]
Needs official review approval first

**Pull request merged**
