### PR TITLE
PUE 2.0 changes for stats and license handling

### PR DESCRIPTION
**Pull request by sc0ttkclark**
https://central.tri.be/issues/72784

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;Update parameters with new ones&quot; | [Checker.php:340](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L340)
:warning: | Comment refers to a TODO task &quot;installed_version&quot; | [Checker.php:350](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L350)
:warning: | Comment refers to a TODO task &quot;key&quot; | [Checker.php:358](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L358)
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Checker.php:436](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L436)
:x: | Barf out, gag me with a spoon! esc_js()!This is for inline javascript, which is against our standards. Use json_encode instead. | [Checker.php:578](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L578)
:x: | Barf out, gag me with a spoon! esc_js()!This is for inline javascript, which is against our standards. Use json_encode instead. | [Checker.php:580](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L580)
:x: | Barf out, gag me with a spoon! esc_js()!This is for inline javascript, which is against our standards. Use json_encode instead. | [Checker.php:583](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L583)
:x: | Barf out, gag me with a spoon! esc_js()!This is for inline javascript, which is against our standards. Use json_encode instead. | [Checker.php:594](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L594)
:x: | Barf out, gag me with a spoon! esc_js()!This is for inline javascript, which is against our standards. Use json_encode instead. | [Checker.php:595](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L595)
:x: | Barf out, gag me with a spoon! esc_js()!This is for inline javascript, which is against our standards. Use json_encode instead. | [Checker.php:597](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L597)
:warning: | Comment refers to a TODO task &quot;Store general static $stats&quot; | [Checker.php:705](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L705)
:warning: | Comment refers to a TODO task &quot;Filter this in Events plugin and add it there instead&quot; | [Checker.php:710](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L710)
:warning: | Comment refers to a TODO task &quot;SKC: Add nonce check&quot; | [Checker.php:914](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L914)
:warning: | Comment refers to a TODO task &quot;SKC: Add nonce check for confirming interaction with $_POST&quot; | [Checker.php:1197](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L1197)
:warning: | Comment refers to a TODO task &quot;handle which key we're checking with&quot; | [Checker.php:1337](https://github.com/moderntribe/tribe-common/blob/a3d33e73d289a59d4b9bdab04dc506b415ab48aa/src/Tribe/PUE/Checker.php#L1337)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space before the last parenthesis | [Checker.php:917](https://github.com/moderntribe/tribe-common/blob/7247e692647a8561bc3790e92b1e468c1fa3db25/src/Tribe/PUE/Checker.php#L917)

> via jenkins/codesniffer-phpcs

**Comment by sc0ttkclark** [comment]
Ready for review

**Comment by bordoni** [comment]
👍

**Pull request merged**
