### PR TITLE
ET-741, PRMTR-206, TCMN-47: Promoter Listeners improvements

### PR DESCRIPTION
**Pull request by mitogh**
Ticket  [ET-741]
Ticket [PRMTR-206]
Ticket: [TCMN-47]

[ET-741]: https://moderntribe.atlassian.net/browse/ET-741

[PRMTR-206]: https://moderntribe.atlassian.net/browse/PRMTR-206

[TCMN-47]: https://moderntribe.atlassian.net/browse/TCMN-47

### CODE REVIEW

**Comment by lucatume** [comment]
@mitogh there's a lot of commit noise in there, was this branch forked off `release/20.03`?

**Comment by mitogh** [comment]
Was based from `master` let me do the Merge dance to cleanup this :dancer:

**Comment by mitogh** [comment]
This PR requires: https://github.com/moderntribe/tribe-common/pull/1313

**Comment by mitogh** [comment]
Hey @sc0ttkclark are you planning to do a release with ET for `common` if so we can include this into that branch instead.

Thanks.

**Comment by sc0ttkclark** [comment]
There are no common changes as of yet for G20.03

**Pull request closed without merging**
