### PR TITLE
Same Slug Archive Dismissible

### PR DESCRIPTION
**Pull request by bordoni**
_Ref:_ [C#39617](https://central.tri.be/issues/39617)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$line_1' | [Archive_Slug_Conflict.php:99](https://github.com/moderntribe/tribe-common/blob/88bcc5ea848d9007fa0814bc9dfc73f642c47866/src/Tribe/Admin/Notice/Archive_Slug_Conflict.php#L99)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$line_2' | [Archive_Slug_Conflict.php:99](https://github.com/moderntribe/tribe-common/blob/88bcc5ea848d9007fa0814bc9dfc73f642c47866/src/Tribe/Admin/Notice/Archive_Slug_Conflict.php#L99)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
:potable_water:

**Comment by bordoni** [comment]
Hey @barryhughes can you re-check this one?

**Comment by borkweb** [comment]
:+1:

**Pull request merged**
