### PR TITLE
Fix: EA > Featured Images Not Importing via CSV

### PR DESCRIPTION
**Pull request by juanfra**
🎫 https://central.tri.be/issues/119269

We were not passing the required vars when setting the featured image via cron job.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:61](https://github.com/moderntribe/tribe-common/blob/aa9ed0dab0bf80c30e00699f1509f27c1feae83a/src/Tribe/Process/Tester.php#L61)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:61](https://github.com/moderntribe/tribe-common/blob/6cbd97d4ca053e04865fb966113e81decf9150b8/src/Tribe/Process/Tester.php#L61)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:61](https://github.com/moderntribe/tribe-common/blob/c0f6e0d65b0818ee4e5d2c037a308e9a6c63eab1/src/Tribe/Process/Tester.php#L61)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/99eb1e314e800dda2bfd0f061b5d23fcf38c828e/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/d383bcff4c4eebb6f8ad3c36de28042e554de293/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/1a4833063c8d360fe636a97dca3b7598e12743dc/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/65ddd5a9560aaa2d5999ca75a4cb8256a946b219/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/818f44c694a1d269be143f214842fce8379d705f/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
@juanfra we're ok with the tests here. I'm closing https://github.com/moderntribe/tribe-common/pull/941 as the tests issue is resolved here.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/0484b1e14d6f3402b933ed780adc91344115d7d2/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/aa90e19458d14cad56ea8fe7bf549ac71dd0892d/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $data_source is never used | [Tester.php:63](https://github.com/moderntribe/tribe-common/blob/fc070d737c2edb0241e149bec4e531e5e8dbd03d/src/Tribe/Process/Tester.php#L63)

> via jenkins/codesniffer-phpcs

**Pull request merged**
