### PR TITLE
add styles for red admin button

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: kinda trasverasl

Adds a red button to our admin styles, straight from https://github.com/jensjns/wp-admin-red-button

### CODE REVIEW

**Comment by bordoni** [comment]
Can we have a Screenshot on this PR? 😆

**Comment by lucatume** [comment]
2016-11-17 at 13 36

**Comment by lucatume** [comment]
there it is

**Comment by bordoni** [comment]
Can we make it match the styles for the `Add more Events` button, but with just red colors?

**Comment by lucatume** [comment]
The "Add more Events" button is just a `button.button`; I do not understand the request. What should change?

**Comment by lucatume** [comment]
2016-11-17 at 13 58
without  gradient

**Comment by bordoni** [comment]
Yeys! 👍

**Pull request merged**
