### PR TITLE
Fix sanitize flag of filter_var in email validation

### PR DESCRIPTION
**Pull request by dharmin**
Fixed incorrect position of arg in filter_var function of email validation in Validate.php

🎫 https://central.tri.be/issues/125915

### CODE REVIEW

**Comment by jrserani** [comment]
_Ref:_ [C#125915](http://central.tri.be/issues/125915)

@dharmin thank you for submitting this - we're taking a look and will let you know if we have any questions or comments :-)

**Comment by sc0ttkclark** [comment]
PR made to merge latest code into @dharmin's branch and added changelog entry

https://github.com/dharmin/tribe-common/pull/1

**Comment by sc0ttkclark** [comment]
Going to do this as part of our own branch, contributions in commits are in-tact.

https://github.com/moderntribe/tribe-common/pull/985

**Comment by niconerd** [comment]
Thanks @dharmin we just wanted to let you know that today we released a new version of Event Tickets containing this fix 👍

**Pull request closed without merging**
