### PR TITLE
WIP - perf(Timezones.php) cache results

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/136624

This PR supports the PR for the same branch on TEC.

### CODE REVIEW

**Comment by lucatume** [comment]
Putting this on-hold as the TEC PR is reviewed.

**Comment by bordoni** [comment]
This change doesn't require the TEC to be an improvement correct? I would go for the merge.

**Comment by lucatume** [comment]
> This change doesn't require the TEC to be an improvement correct? I would go for the merge.

Yes, we can merge straight away.

**Comment by lucatume** [comment]
Rebased on `release/B19.15`, updated and re-tested, all passing, merging.

**Pull request merged**
