### PR TITLE
Merge latest release branch into bucket/recurrence

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/101787

This PR merges latest common (`release/M18.05` at the time of this writing) into `bucket/recurrence` to solve merge conflicts and restore the tests.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $set_b is never used | [Average_Proximity_Start_Detector.php:37](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L37)
:warning: | The method parameter $set_a is never used | [Average_Proximity_Start_Detector.php:83](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L83)
:warning: | The method parameter $set_b is never used | [Average_Proximity_Start_Detector.php:83](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L83)
:warning: | The method parameter $b_set is never used | [Closest_Unique_Start_Detector.php:56](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L56)
:warning: | The method parameter $set_b is never used | [Closest_Unique_Start_Detector.php:95](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L95)
:warning: | The method parameter $set_b is never used | [Closest_Unique_Start_Detector.php:209](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L209)
:warning: | The method parameter $segment is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $b_ends is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $report is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $set_b is never used | [Detection_Strategy.php:77](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Detection_Strategy.php#L77)
:warning: | The method parameter $set_b is never used | [Detection_Strategy.php:183](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Detection_Strategy.php#L183)
:warning: | The method parameter $b_set is never used | [Detection_Strategy.php:249](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Detection_Strategy.php#L249)
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Median_Proximity_Start_Detector.php:19](https://github.com/moderntribe/tribe-common/blob/fbbd71bd731962ae928645503982a227c350fcf3/src/Tribe/Collisions/Median_Proximity_Start_Detector.php#L19)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
The bot comment on PHP 5.2 compat is wonky, this is the code in question:

```php
$ne_starts_count = count( $ne_starts );

if ( empty ( $ne_starts_count ) ) {
    return $median;
}
```

**Comment by lucatume** [comment]
Putting this On Hold while I work on TEC and PRO: I might need to make further modifications.

**Comment by bordoni** [comment]
That specific sniffer is wonky at times. Ignore it.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $set_b is never used | [Average_Proximity_Start_Detector.php:37](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L37)
:warning: | The method parameter $set_a is never used | [Average_Proximity_Start_Detector.php:83](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L83)
:warning: | The method parameter $set_b is never used | [Average_Proximity_Start_Detector.php:83](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L83)
:warning: | The method parameter $b_set is never used | [Closest_Unique_Start_Detector.php:56](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L56)
:warning: | The method parameter $set_b is never used | [Closest_Unique_Start_Detector.php:95](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L95)
:warning: | The method parameter $set_b is never used | [Closest_Unique_Start_Detector.php:209](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L209)
:warning: | The method parameter $segment is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $b_ends is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $report is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $set_b is never used | [Detection_Strategy.php:77](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Detection_Strategy.php#L77)
:warning: | The method parameter $set_b is never used | [Detection_Strategy.php:183](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Detection_Strategy.php#L183)
:warning: | The method parameter $b_set is never used | [Detection_Strategy.php:249](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Detection_Strategy.php#L249)
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Median_Proximity_Start_Detector.php:19](https://github.com/moderntribe/tribe-common/blob/1ec3914d6f8cd5b97aeca9b1d431b80d25800ad5/src/Tribe/Collisions/Median_Proximity_Start_Detector.php#L19)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $set_b is never used | [Average_Proximity_Start_Detector.php:37](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L37)
:warning: | The method parameter $set_a is never used | [Average_Proximity_Start_Detector.php:83](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L83)
:warning: | The method parameter $set_b is never used | [Average_Proximity_Start_Detector.php:83](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Average_Proximity_Start_Detector.php#L83)
:warning: | The method parameter $b_set is never used | [Closest_Unique_Start_Detector.php:56](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L56)
:warning: | The method parameter $set_b is never used | [Closest_Unique_Start_Detector.php:95](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L95)
:warning: | The method parameter $set_b is never used | [Closest_Unique_Start_Detector.php:209](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L209)
:warning: | The method parameter $segment is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $b_ends is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $report is never used | [Closest_Unique_Start_Detector.php:229](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Closest_Unique_Start_Detector.php#L229)
:warning: | The method parameter $set_b is never used | [Detection_Strategy.php:77](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Detection_Strategy.php#L77)
:warning: | The method parameter $set_b is never used | [Detection_Strategy.php:183](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Detection_Strategy.php#L183)
:warning: | The method parameter $b_set is never used | [Detection_Strategy.php:249](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Detection_Strategy.php#L249)
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Median_Proximity_Start_Detector.php:19](https://github.com/moderntribe/tribe-common/blob/6b4630f7d465c91bbb0316843313ca8e5c559269/src/Tribe/Collisions/Median_Proximity_Start_Detector.php#L19)

> via jenkins/codesniffer-phpcs

**Pull request merged**
