### PR TITLE
Fix/118994 tweak post id helper

### PR DESCRIPTION
**Pull request by cliffordp**
https://central.tri.be/issues/118994

If pass _null or 0_, then determine the Post ID. The only real change is from:
`is_numeric( $post ) > 0`
to:
`is_numeric( $post ) && intval( $post ) > 0`

Everything else is just formatting.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $old_value is never used | [Cache_Listener.php:59](https://github.com/moderntribe/tribe-common/blob/c82fd177109559f0ba65b3f1e25a350fe25d25f8/src/Tribe/Cache_Listener.php#L59)
:warning: | The method parameter $value is never used | [Cache_Listener.php:59](https://github.com/moderntribe/tribe-common/blob/c82fd177109559f0ba65b3f1e25a350fe25d25f8/src/Tribe/Cache_Listener.php#L59)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *M18.18*, but this was pull requested against *release/M18.17*.

**Comment by mitogh** [comment]
Wanna reopen this for the next MR?

**Comment by mitogh** [comment]
Some conflicts @cliffordp

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for **, but this was pull requested against *release/M18.18*.

**Comment by cliffordp** [comment]
@mitogh What conflicts do you see? I saw Jeff said this needs a test. Is that what you meant?

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for **, but this was pull requested against *release/M18.18*.

**Comment by mitogh** [comment]
No it was conflicts on the branch as it was out of date on the past.

I think you only need to make sure your branch is up to date with the latest code where the branch is pointing to avoid any merge conflicts.

Let me know if you have additional questions @cliffordp 👍

**Comment by cliffordp** [comment]
https://github.com/moderntribe/tribe-common/pull/932 replaces this one

**Pull request closed without merging**
