### PR TITLE
Allow to hook into the cost before is returned

### PR DESCRIPTION
**Pull request by mitogh**
**Ticket** https://central.tri.be/issues/70361

Make sure the cost is filterable in order to be changed by other
providers.

### CODE REVIEW

**Comment by mitogh** [comment]
**Note** Not sure if `master` is the right branch for this PR, please let me know if we need to update it, thanks.

**Comment by bordoni** [comment]
We don't merge this one until we have a release.

**Comment by mitogh** [comment]
Okay this is required for https://github.com/moderntribe/event-tickets/pull/657 not sure how we should handle it tho @bordoni

**Comment by barryhughes** [comment]
[#70361](https://central.tri.be/issues/70361) is a TC ticket - should we create a `bucket/tribe-commerce` branch for this repo and target that?

**Comment by mitogh** [comment]
That works for me not sure what @bordoni thinks?

**Comment by bordoni** [comment]
I like the idea. Let's go for that branch.

**Comment by mitogh** [comment]
Merging it as the base is no longer `master`

**Pull request merged**
