### PR TITLE
In the context of tribe-common, there is no pluginName of note

### PR DESCRIPTION
**Pull request by borkweb**
See: https://central.tri.be/issues/41695

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Don't leave error_log lying around | [Debug.php:36](https://github.com/moderntribe/tribe-common/blob/2fc64a60c843635a1542fa123e952989fb592c4d/src/Tribe/Debug.php#L36)
:x: | Don't leave error_log lying around | [Debug.php:38](https://github.com/moderntribe/tribe-common/blob/2fc64a60c843635a1542fa123e952989fb592c4d/src/Tribe/Debug.php#L38)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
Why not mention that the message came from Common, or at least from which common it came from.

**Comment by borkweb** [comment]
Yeah, that seems reasonable. Added.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Don't leave error_log lying around | [Debug.php:37](https://github.com/moderntribe/tribe-common/blob/98b936939f18ac55f0dd3702be563b108546aedf/src/Tribe/Debug.php#L37)
:x: | Don't leave error_log lying around | [Debug.php:39](https://github.com/moderntribe/tribe-common/blob/98b936939f18ac55f0dd3702be563b108546aedf/src/Tribe/Debug.php#L39)

> via jenkins/codesniffer-phpcs

**Pull request merged**
